### ISSUE TITLE
Possible to make the menu overlap the underlying view?

### ISSUE THREAD

**Issue by karlingen** [ThornTechPublic/LeftSlideoutMenu#3]
Instead of pushing it to the side, how can I make it overlap the entire content?

Like this https://github.com/dekatotoro/SlideMenuControllerSwift

**Comment by chenr2** [comment]
Unfortunately, my slideout menu is setup for panning the whole thing side-to-side. 

I skimmed through code in the link you provided, and it's actually a very good find.  Thank you!  Does dekatotoro's slideout implementation work for your needs, since the slideout menus overlap the main content?

**Comment by karlingen** [comment]
It sure does :)

**Comment by chenr2** [comment]
@karlingen So, this question has been hanging over my head for some time, and is part of what inspired me to create a new slideout menu that supports customizable animations: 
http://www.thorntech.com/2016/03/ios-tutorial-make-interactive-slide-menu-swift

The animation in the tutorial currently has the menu underlapping the main content. But it should be easy for anyone to customize the animation to overlap, come out of the right side, or add 3D effects, etc.

**Comment by karlingen** [comment]
Wow, amazing news! Will definitely try this out :)
